Models/Ayet.cs
namespace GununAyeti.Models
{
    public class Ayet
    {
        public int Id { get; set; }
        public String? ArapcaMetin { get; set; }=String.Empty;
        public String? Aciklama { get; set;}=String.Empty;
        public String? SureIsmi { get; set;}=String.Empty;
        public int AyetNo { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace GununAyeti.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/RepositoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace GununAyeti.Models
{
    // Veritabanı bağlantısını sağlamak için RepositoryContext sınıfını kullanıyoruz.
    public class RepositoryContext : DbContext
    {
        public DbSet<Ayet> Ayetler { get; set; } // Ayetler tablosunu oluşturuyoruz.
        // Veritabanı bağlantısını sağlamak için RepositoryContext sınıfını kullanıyoruz.
        public RepositoryContext(DbContextOptions<RepositoryContext> options)
        : base(options) // Veritabanı bağlantısını sağlamak için base sınıfının constructor metodunu kullanıyoruz.
        {
            
        }
    }
}

Controllers/AyetController.cs
using GununAyeti.Models;
using Microsoft.AspNetCore.Mvc;

namespace GununAyeti.Controllers
{
    public class AyetController : Controller
    {
        // Veritabanı bağlantısını sağlamak için RepositoryContext sınıfını kullanıyoruz.
        private readonly RepositoryContext _context; // RepositoryContext sınıfından bir nesne oluşturuyoruz.

        public AyetController(RepositoryContext context)
        {
            _context = context; // RepositoryContext sınıfını kullanabilmek için constructor metodu ile bir nesne oluşturuyoruz.
        }

        public IActionResult Index()
        {
            var model= _context.Ayetler.ToList(); // Ayetler tablosundaki tüm verileri alıyoruz.
            return View(model);
        }

        public IActionResult Get(int id)
        {
            // Id'si verilen ayeti getiriyoruz.
            Ayet ayet = _context.Ayetler.First(a => a.Id==id); 
            return View(ayet);
        }

        public IActionResult GununAyeti()
        {
            Random random = new Random(); // Random sınıfından bir nesne oluşturuyoruz.
            int count = _context.Ayetler.Count(); // Ayetler tablosundaki kayıt sayısını alıyoruz.
            int id  = random.Next(1, count); // 1 ile 4 arasında rastgele bir sayı oluşturuyoruz.
            Ayet ayet = _context.Ayetler.First(a => a.Id==id);  // Id'si rastgele oluşturulan sayıya eşit olan ayeti getiriyoruz.
            return View(ayet); // Ayet nesnesini döndürüyoruz.
        }

        public IActionResult Kayit() // Kayıt sayfasını göstermek için bir action metodu oluşturuyoruz.
        {
            return View(); // Kayıt sayfasını döndürüyoruz.
        }

        [HttpPost] // Formdan gelen verileri almak için HttpPost attribute'ünü kullanıyoruz.
        public IActionResult Kayit(Ayet ayet) // Formdan gelen verileri almak için Ayet sınıfından bir nesne oluşturuyoruz.
        {
            // Veritabanına kayıt işlemi
            _context.Ayetler.Add(ayet); // Ayet nesnesini veritabanına ekliyoruz.
            _context.SaveChanges(); // Değişiklikleri kaydediyoruz.
            return RedirectToAction("Index"); // Index sayfasına yönlendirme yapıyoruz.
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using GununAyeti.Models;

namespace GununAyeti.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Ayet/Get.cshtml
@{
    ViewData["Title"] = "Günün Ayeti";
}

@model Ayet

<h3>Günün Ayeti</nav></nav></h3>
<p>@Model.ArapcaMetin</p>
<p>@Model.Aciklama</p>
<p>@Model.SureIsmi</p>
<p>@Model.AyetNo</p>

Views/Ayet/GununAyeti.cshtml
@{
    ViewData["Title"] = "Günün Ayeti";
}

@model Ayet

<h3>Günün Ayeti</h3>
<p>@Model.ArapcaMetin</p>
<p>@Model.Aciklama</p>
<p>@Model.SureIsmi, @Model.AyetNo</p>

Views/Ayet/Index.cshtml
@{
    ViewData["Title"] = "Ayet Kaydı";
}

@model List<Ayet>
    
@foreach (Ayet item in Model)
{
   <div>
        <p>@item.ArapcaMetin</p>
        <p>@item.Aciklama</p>
        <p>
            <a asp-action="Get" asp-controller="Ayet" asp-route-id="@item.Id">Detay</a>
        </p>
    </div>
}      

Views/Ayet/Kayit.cshtml
@{
    ViewData["Title"] = "Ayet Kaydı";
}

@model Ayet 

<h2>Ayet Kaydı</h2>

<form asp-action="Kayit" method="post"> 
    <div class="form-group my-2">
        <label asp-for="ArapcaMetin" class="control-label">Arapça Metin:</label>
        <textarea asp-for="ArapcaMetin" class="form-control"></textarea>
        <span asp-validation-for="ArapcaMetin" class="text-danger"></span>
    </div>
    <div class="form-group my-2">
        <label asp-for="Aciklama" class="control-label">Meali Şerifi:</label>
        <textarea asp-for="Aciklama" class="form-control"></textarea>
        <span asp-validation-for="Aciklama" class="text-danger"></span>
    </div>
    <div class="form-group my-2">
        <label asp-for="SureIsmi" class="control-label">Sure İsmi:</label>
        <input asp-for="SureIsmi" class="form-control" />
        <span asp-validation-for="SureIsmi" class="text-danger"></span>
    </div>   
    <div class="form-group my-2">
        <label asp-for="AyetNo" class="control-label">Ayet Numarası:</label>
        <input asp-for="AyetNo" class="form-control" />
        <span asp-validation-for="AyetNo" class="text-danger"></span>
    </div> 
    <div class="form-group my-2">
        <input type="submit" value="Kaydet" class="btn btn-primary" />
        <input type="reset" value="Temizle" class="btn btn-warning" />
    </div>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Hoş Geldiniz</h1>
    <p>Tasarım & Kodlama  <a href="https://www.nuritiras.com.tr">Nuri TIRAŞ </a></p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Günün Ayeti</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GununAyeti.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Ayet" asp-action="GununAyeti">Günün Ayeti</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ayet" asp-action="Index">Ayetler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ayet" asp-action="Kayit">Ayet Kayıt</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Günün Ayeti - <a asp-area="" asp-controller="Ayet" asp-action="Index">Ayetler</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>